[PHP]
display_errors = Off
display_startup_errors = Off
log_errors = On
error_reporting = E_ALL
memory_limit = 256M
upload_max_filesize = 50M
post_max_size = 52M
max_execution_time = 180
max_input_time = 180
date.timezone = America/Caracas
expose_php = Off
