# nginx actúa como puente entre Traefik (host network) y el frontend (bridge network)
# Escucha en el puerto 8091 del HOST → reenvía al frontend en su IP fija

server {
    listen 8091;
    server_name _;

    location / {
        proxy_pass         http://172.30.0.10;   # IP fija del frontend en app-network
        proxy_http_version 1.1;

        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;

        proxy_connect_timeout 10s;
        proxy_read_timeout    30s;
    }
}
